spring:
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
  application:
    name: jasypt
  datasource:
    driver-class-name: org.h2.Driver
    username: JASYPT(u9Rs+JXUsfqfYrs49kE+T2a3legikuLycZzxMN2YcWfPYBK3KvjtWXfLSaQ8qmDN)
    password: JASYPT(qFoLH4wEDqhctovFvsAe0WyrFde3BODDAYs/qLAMZ+gViAZv7+V/GVgrxyVTdBeN)
    name: jasypt
    url: jdbc:h2:~/.h2/db/history;AUTO_SERVER=TRUE
  h2:
    console:
      path: /h2-console/histories
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: jasypt!@#_H2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  sql:
    init:
      schema-locations: classpath*:/database/schema/schema.sql
      continue-on-error: true
      mode: always
      platform: H2
      encoding: UTF-8
      password: jasypt!@#_H2
      username: jasypt
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # generate-ddl: false
    show-sql: true
    hibernate:
      # 自动建表
      ddl-auto: update
mybatis-plus:
  mapper-locations: classpath*:cn/com/mooyea/jasypt/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
jasypt:
  encryptor:
    password: skyvis!@#_jasypt
    algorithm: PBEWITHHMACSHA512ANDAES_256
    pool-size: 1
    string-output-type: base64
    property:
      # 加密前缀
      prefix: JASYPT(
      # 加密后缀
      suffix: )
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    provider-name: SunJCE
    bean: customEncryption
